///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace keepass5
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the keepass5Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    [RepositoryFolder("2f7e0af1-f63c-4f9c-804a-2984e8981fbe")]
    public partial class keepass5Repository : RepoGenBaseFolder
    {
        static keepass5Repository instance = new keepass5Repository();
        keepass5RepositoryFolders.KeyPromptFormAppFolder _keypromptform;
        keepass5RepositoryFolders.MainFormAppFolder _mainform;
        keepass5RepositoryFolders.KeePassAppFolder _keepass;
        keepass5RepositoryFolders.PwEntryFormAppFolder _pwentryform;

        /// <summary>
        /// Gets the singleton class instance representing the keepass5Repository element repository.
        /// </summary>
        [RepositoryFolder("2f7e0af1-f63c-4f9c-804a-2984e8981fbe")]
        public static keepass5Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public keepass5Repository() 
            : base("keepass5Repository", "/", null, 0, false, "2f7e0af1-f63c-4f9c-804a-2984e8981fbe", ".\\RepositoryImages\\keepass5Repository2f7e0af1.rximgres")
        {
            _keypromptform = new keepass5RepositoryFolders.KeyPromptFormAppFolder(this);
            _mainform = new keepass5RepositoryFolders.MainFormAppFolder(this);
            _keepass = new keepass5RepositoryFolders.KeePassAppFolder(this);
            _pwentryform = new keepass5RepositoryFolders.PwEntryFormAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("2f7e0af1-f63c-4f9c-804a-2984e8981fbe")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The KeyPromptForm folder.
        /// </summary>
        [RepositoryFolder("75e30ee6-628e-4a2c-91d5-6de720add1c3")]
        public virtual keepass5RepositoryFolders.KeyPromptFormAppFolder KeyPromptForm
        {
            get { return _keypromptform; }
        }

        /// <summary>
        /// The MainForm folder.
        /// </summary>
        [RepositoryFolder("c1bd3f10-ca28-4b76-a8e3-eda7cd5dd0e7")]
        public virtual keepass5RepositoryFolders.MainFormAppFolder MainForm
        {
            get { return _mainform; }
        }

        /// <summary>
        /// The KeePass folder.
        /// </summary>
        [RepositoryFolder("c5927b0b-009b-42ab-977d-f3410a0dea28")]
        public virtual keepass5RepositoryFolders.KeePassAppFolder KeePass
        {
            get { return _keepass; }
        }

        /// <summary>
        /// The PwEntryForm folder.
        /// </summary>
        [RepositoryFolder("17a39300-2af6-4505-9ffc-75ec25c284da")]
        public virtual keepass5RepositoryFolders.PwEntryFormAppFolder PwEntryForm
        {
            get { return _pwentryform; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    public partial class keepass5RepositoryFolders
    {
        /// <summary>
        /// The KeyPromptFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("75e30ee6-628e-4a2c-91d5-6de720add1c3")]
        public partial class KeyPromptFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _mcbpasswordInfo;
            RepoItemInfo _textInfo;
            RepoItemInfo _mbtnokInfo;

            /// <summary>
            /// Creates a new KeyPromptForm  folder.
            /// </summary>
            public KeyPromptFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("KeyPromptForm", "/form[@controlname='KeyPromptForm']", parentFolder, 30000, null, true, "75e30ee6-628e-4a2c-91d5-6de720add1c3", "")
            {
                _mcbpasswordInfo = new RepoItemInfo(this, "MCbPassword", "checkbox[@controlname='m_cbPassword']", 30000, null, "4c70e6af-270e-4475-8e51-41bb65cc209b");
                _textInfo = new RepoItemInfo(this, "Text", "?/?/text[@accessiblerole='Text']", 30000, null, "2cd7ac20-df91-408d-8f37-5fd8f3cf740c");
                _mbtnokInfo = new RepoItemInfo(this, "MBtnOK", "button[@controlname='m_btnOK']", 30000, null, "6ea944bb-5d0d-4782-b479-4203a8fa69f3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("75e30ee6-628e-4a2c-91d5-6de720add1c3")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("75e30ee6-628e-4a2c-91d5-6de720add1c3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MCbPassword item.
            /// </summary>
            [RepositoryItem("4c70e6af-270e-4475-8e51-41bb65cc209b")]
            public virtual Ranorex.CheckBox MCbPassword
            {
                get
                {
                    return _mcbpasswordInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The MCbPassword item info.
            /// </summary>
            [RepositoryItemInfo("4c70e6af-270e-4475-8e51-41bb65cc209b")]
            public virtual RepoItemInfo MCbPasswordInfo
            {
                get
                {
                    return _mcbpasswordInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("2cd7ac20-df91-408d-8f37-5fd8f3cf740c")]
            public virtual Ranorex.Text Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("2cd7ac20-df91-408d-8f37-5fd8f3cf740c")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The MBtnOK item.
            /// </summary>
            [RepositoryItem("6ea944bb-5d0d-4782-b479-4203a8fa69f3")]
            public virtual Ranorex.Button MBtnOK
            {
                get
                {
                    return _mbtnokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MBtnOK item info.
            /// </summary>
            [RepositoryItemInfo("6ea944bb-5d0d-4782-b479-4203a8fa69f3")]
            public virtual RepoItemInfo MBtnOKInfo
            {
                get
                {
                    return _mbtnokInfo;
                }
            }
        }

        /// <summary>
        /// The MainFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("c1bd3f10-ca28-4b76-a8e3-eda7cd5dd0e7")]
        public partial class MainFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _editInfo;
            RepoItemInfo _fileInfo;
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new MainForm  folder.
            /// </summary>
            public MainFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MainForm", "/form[@controlname='MainForm']", parentFolder, 30000, null, true, "c1bd3f10-ca28-4b76-a8e3-eda7cd5dd0e7", "")
            {
                _editInfo = new RepoItemInfo(this, "Edit", "?/?/menuitem[@accessiblename='Edit']", 30000, null, "569a0baa-8444-4c37-9139-da96403f39cc");
                _fileInfo = new RepoItemInfo(this, "File", "?/?/menuitem[@accessiblename='File']", 30000, null, "49008708-efc4-4ca1-b869-b932b45ed64b");
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@accessiblename='Close']", 30000, null, "f835e904-7720-4c5b-afa3-952d68dddf35");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c1bd3f10-ca28-4b76-a8e3-eda7cd5dd0e7")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c1bd3f10-ca28-4b76-a8e3-eda7cd5dd0e7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Edit item.
            /// </summary>
            [RepositoryItem("569a0baa-8444-4c37-9139-da96403f39cc")]
            public virtual Ranorex.MenuItem Edit
            {
                get
                {
                    return _editInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Edit item info.
            /// </summary>
            [RepositoryItemInfo("569a0baa-8444-4c37-9139-da96403f39cc")]
            public virtual RepoItemInfo EditInfo
            {
                get
                {
                    return _editInfo;
                }
            }

            /// <summary>
            /// The File item.
            /// </summary>
            [RepositoryItem("49008708-efc4-4ca1-b869-b932b45ed64b")]
            public virtual Ranorex.MenuItem File
            {
                get
                {
                    return _fileInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The File item info.
            /// </summary>
            [RepositoryItemInfo("49008708-efc4-4ca1-b869-b932b45ed64b")]
            public virtual RepoItemInfo FileInfo
            {
                get
                {
                    return _fileInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("f835e904-7720-4c5b-afa3-952d68dddf35")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("f835e904-7720-4c5b-afa3-952d68dddf35")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

        /// <summary>
        /// The KeePassAppFolder folder.
        /// </summary>
        [RepositoryFolder("c5927b0b-009b-42ab-977d-f3410a0dea28")]
        public partial class KeePassAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _addentryInfo;
            RepoItemInfo _selectallInfo;
            RepoItemInfo _menuitem2weeksInfo;
            RepoItemInfo _saveInfo;

            /// <summary>
            /// Creates a new KeePass  folder.
            /// </summary>
            public KeePassAppFolder(RepoGenBaseFolder parentFolder) :
                    base("KeePass", "/contextmenu[@processname='KeePass']", parentFolder, 30000, null, true, "c5927b0b-009b-42ab-977d-f3410a0dea28", "")
            {
                _addentryInfo = new RepoItemInfo(this, "AddEntry", "menuitem[@accessiblename='Add Entry...']", 30000, null, "ebdbcfbb-8420-4e57-b4d2-8d7451d070cb");
                _selectallInfo = new RepoItemInfo(this, "SelectAll", "?/?/menuitem[@accessiblename='Select All']", 30000, null, "003e4737-25de-402b-96d8-3568421b06fa");
                _menuitem2weeksInfo = new RepoItemInfo(this, "MenuItem2Weeks", "menuitem[@accessiblename='2 Weeks']", 30000, null, "38aff004-7cae-4146-a198-6b158fc351bf");
                _saveInfo = new RepoItemInfo(this, "Save", "menuitem[@accessiblename='Save']", 30000, null, "bff07127-1827-4496-80a8-201e805e6752");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c5927b0b-009b-42ab-977d-f3410a0dea28")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c5927b0b-009b-42ab-977d-f3410a0dea28")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AddEntry item.
            /// </summary>
            [RepositoryItem("ebdbcfbb-8420-4e57-b4d2-8d7451d070cb")]
            public virtual Ranorex.MenuItem AddEntry
            {
                get
                {
                    return _addentryInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The AddEntry item info.
            /// </summary>
            [RepositoryItemInfo("ebdbcfbb-8420-4e57-b4d2-8d7451d070cb")]
            public virtual RepoItemInfo AddEntryInfo
            {
                get
                {
                    return _addentryInfo;
                }
            }

            /// <summary>
            /// The SelectAll item.
            /// </summary>
            [RepositoryItem("003e4737-25de-402b-96d8-3568421b06fa")]
            public virtual Ranorex.MenuItem SelectAll
            {
                get
                {
                    return _selectallInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The SelectAll item info.
            /// </summary>
            [RepositoryItemInfo("003e4737-25de-402b-96d8-3568421b06fa")]
            public virtual RepoItemInfo SelectAllInfo
            {
                get
                {
                    return _selectallInfo;
                }
            }

            /// <summary>
            /// The MenuItem2Weeks item.
            /// </summary>
            [RepositoryItem("38aff004-7cae-4146-a198-6b158fc351bf")]
            public virtual Ranorex.MenuItem MenuItem2Weeks
            {
                get
                {
                    return _menuitem2weeksInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuItem2Weeks item info.
            /// </summary>
            [RepositoryItemInfo("38aff004-7cae-4146-a198-6b158fc351bf")]
            public virtual RepoItemInfo MenuItem2WeeksInfo
            {
                get
                {
                    return _menuitem2weeksInfo;
                }
            }

            /// <summary>
            /// The Save item.
            /// </summary>
            [RepositoryItem("bff07127-1827-4496-80a8-201e805e6752")]
            public virtual Ranorex.MenuItem Save
            {
                get
                {
                    return _saveInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Save item info.
            /// </summary>
            [RepositoryItemInfo("bff07127-1827-4496-80a8-201e805e6752")]
            public virtual RepoItemInfo SaveInfo
            {
                get
                {
                    return _saveInfo;
                }
            }
        }

        /// <summary>
        /// The PwEntryFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("17a39300-2af6-4505-9ffc-75ec25c284da")]
        public partial class PwEntryFormAppFolder : RepoGenBaseFolder
        {
            keepass5RepositoryFolders.MTabEntryFolder _mtabentry;
            RepoItemInfo _textInfo;
            RepoItemInfo _mbtnstandardexpiresInfo;
            RepoItemInfo _mbtnokInfo;

            /// <summary>
            /// Creates a new PwEntryForm  folder.
            /// </summary>
            public PwEntryFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PwEntryForm", "/form[@controlname='PwEntryForm']", parentFolder, 30000, null, true, "17a39300-2af6-4505-9ffc-75ec25c284da", "")
            {
                _mtabentry = new keepass5RepositoryFolders.MTabEntryFolder(this);
                _textInfo = new RepoItemInfo(this, "Text", "?/?/tabpage[@controlname='m_tabEntry']/text[@controlname='m_tbTitle']/text[@accessiblerole='Text']", 30000, null, "e5502b41-071b-42c5-b0ee-8348e5f20da0");
                _mbtnstandardexpiresInfo = new RepoItemInfo(this, "MBtnStandardExpires", "?/?/tabpage[@controlname='m_tabEntry']/button[@controlname='m_btnStandardExpires']", 30000, null, "05beab19-9601-4ab1-987d-00063615aee0");
                _mbtnokInfo = new RepoItemInfo(this, "MBtnOK", "button[@controlname='m_btnOK']", 30000, null, "2bee6f7e-9bbf-438a-a990-2d5efdd107b9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("17a39300-2af6-4505-9ffc-75ec25c284da")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("17a39300-2af6-4505-9ffc-75ec25c284da")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("e5502b41-071b-42c5-b0ee-8348e5f20da0")]
            public virtual Ranorex.Text Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("e5502b41-071b-42c5-b0ee-8348e5f20da0")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The MBtnStandardExpires item.
            /// </summary>
            [RepositoryItem("05beab19-9601-4ab1-987d-00063615aee0")]
            public virtual Ranorex.Button MBtnStandardExpires
            {
                get
                {
                    return _mbtnstandardexpiresInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MBtnStandardExpires item info.
            /// </summary>
            [RepositoryItemInfo("05beab19-9601-4ab1-987d-00063615aee0")]
            public virtual RepoItemInfo MBtnStandardExpiresInfo
            {
                get
                {
                    return _mbtnstandardexpiresInfo;
                }
            }

            /// <summary>
            /// The MBtnOK item.
            /// </summary>
            [RepositoryItem("2bee6f7e-9bbf-438a-a990-2d5efdd107b9")]
            public virtual Ranorex.Button MBtnOK
            {
                get
                {
                    return _mbtnokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MBtnOK item info.
            /// </summary>
            [RepositoryItemInfo("2bee6f7e-9bbf-438a-a990-2d5efdd107b9")]
            public virtual RepoItemInfo MBtnOKInfo
            {
                get
                {
                    return _mbtnokInfo;
                }
            }

            /// <summary>
            /// The MTabEntry folder.
            /// </summary>
            [RepositoryFolder("ebf993a9-23b2-4a45-9161-9e85b7c95192")]
            public virtual keepass5RepositoryFolders.MTabEntryFolder MTabEntry
            {
                get { return _mtabentry; }
            }
        }

        /// <summary>
        /// The MTabEntryFolder folder.
        /// </summary>
        [RepositoryFolder("ebf993a9-23b2-4a45-9161-9e85b7c95192")]
        public partial class MTabEntryFolder : RepoGenBaseFolder
        {
            RepoItemInfo _notesInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _repeatInfo;
            RepoItemInfo _urlInfo;
            RepoItemInfo _usernameInfo;

            /// <summary>
            /// Creates a new MTabEntry  folder.
            /// </summary>
            public MTabEntryFolder(RepoGenBaseFolder parentFolder) :
                    base("MTabEntry", "?/?/tabpage[@controlname='m_tabEntry']", parentFolder, 30000, null, false, "ebf993a9-23b2-4a45-9161-9e85b7c95192", "")
            {
                _notesInfo = new RepoItemInfo(this, "Notes", "?/?/text[@accessiblename='Notes:']", 30000, null, "f75c326a-ffed-4cc0-8d43-263f1934758b");
                _passwordInfo = new RepoItemInfo(this, "Password", "?/?/text[@accessiblename='Password:']", 30000, null, "a19a6424-660a-41ce-b47b-c6c9ad2b92d7");
                _repeatInfo = new RepoItemInfo(this, "Repeat", "?/?/text[@accessiblename='Repeat:']", 30000, null, "ab58fd40-2edb-4329-9c68-d58d7e517925");
                _urlInfo = new RepoItemInfo(this, "URL", "?/?/text[@accessiblename='URL:']", 30000, null, "52b3b9f6-7513-42d1-8840-62ecfc2f1c98");
                _usernameInfo = new RepoItemInfo(this, "UserName", "?/?/text[@accessiblename='User name:']", 30000, null, "48c4e098-83b0-4250-85ae-3d8cc3cebc72");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ebf993a9-23b2-4a45-9161-9e85b7c95192")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ebf993a9-23b2-4a45-9161-9e85b7c95192")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Notes item.
            /// </summary>
            [RepositoryItem("f75c326a-ffed-4cc0-8d43-263f1934758b")]
            public virtual Ranorex.Text Notes
            {
                get
                {
                    return _notesInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Notes item info.
            /// </summary>
            [RepositoryItemInfo("f75c326a-ffed-4cc0-8d43-263f1934758b")]
            public virtual RepoItemInfo NotesInfo
            {
                get
                {
                    return _notesInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("a19a6424-660a-41ce-b47b-c6c9ad2b92d7")]
            public virtual Ranorex.Text Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("a19a6424-660a-41ce-b47b-c6c9ad2b92d7")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The Repeat item.
            /// </summary>
            [RepositoryItem("ab58fd40-2edb-4329-9c68-d58d7e517925")]
            public virtual Ranorex.Text Repeat
            {
                get
                {
                    return _repeatInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Repeat item info.
            /// </summary>
            [RepositoryItemInfo("ab58fd40-2edb-4329-9c68-d58d7e517925")]
            public virtual RepoItemInfo RepeatInfo
            {
                get
                {
                    return _repeatInfo;
                }
            }

            /// <summary>
            /// The URL item.
            /// </summary>
            [RepositoryItem("52b3b9f6-7513-42d1-8840-62ecfc2f1c98")]
            public virtual Ranorex.Text URL
            {
                get
                {
                    return _urlInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The URL item info.
            /// </summary>
            [RepositoryItemInfo("52b3b9f6-7513-42d1-8840-62ecfc2f1c98")]
            public virtual RepoItemInfo URLInfo
            {
                get
                {
                    return _urlInfo;
                }
            }

            /// <summary>
            /// The UserName item.
            /// </summary>
            [RepositoryItem("48c4e098-83b0-4250-85ae-3d8cc3cebc72")]
            public virtual Ranorex.Text UserName
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The UserName item info.
            /// </summary>
            [RepositoryItemInfo("48c4e098-83b0-4250-85ae-3d8cc3cebc72")]
            public virtual RepoItemInfo UserNameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}