///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace keepass5
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("cdf15c7e-b7e5-4e29-a8c4-d6395a69720b", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the keepass5Repository repository.
        /// </summary>
        public static keepass5Repository repo = keepass5Repository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'F:\\KeePass Password Safe 2\\KeePass.exe' with arguments '' in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication("F:\\KeePass Password Safe 2\\KeePass.exe", "", "F:\\KeePass Password Safe 2", false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'KeyPromptForm.MCbPassword' at 7;9.", repo.KeyPromptForm.MCbPasswordInfo, new RecordItemIndex(1));
            repo.KeyPromptForm.MCbPassword.Click("7;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'KeyPromptForm.Text' at 26;4.", repo.KeyPromptForm.TextInfo, new RecordItemIndex(2));
            repo.KeyPromptForm.Text.Click("26;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'rx' with focus on 'KeyPromptForm.Text'.", repo.KeyPromptForm.TextInfo, new RecordItemIndex(3));
            repo.KeyPromptForm.Text.PressKeys("rx");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'KeyPromptForm.MBtnOK' at 43;14.", repo.KeyPromptForm.MBtnOKInfo, new RecordItemIndex(4));
            repo.KeyPromptForm.MBtnOK.Click("43;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.Edit' at 12;13.", repo.MainForm.EditInfo, new RecordItemIndex(5));
            repo.MainForm.Edit.Click("12;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'KeePass.AddEntry' at 45;2.", repo.KeePass.AddEntryInfo, new RecordItemIndex(6));
            repo.KeePass.AddEntry.Click("45;2");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PwEntryForm.Text' at 50;11.", repo.PwEntryForm.TextInfo, new RecordItemIndex(7));
            repo.PwEntryForm.Text.Click("50;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'user{Space}login' with focus on 'PwEntryForm.Text'.", repo.PwEntryForm.TextInfo, new RecordItemIndex(8));
            repo.PwEntryForm.Text.PressKeys("user{Space}login");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PwEntryForm.MTabEntry.UserName' at 42;7.", repo.PwEntryForm.MTabEntry.UserNameInfo, new RecordItemIndex(9));
            repo.PwEntryForm.MTabEntry.UserName.Click("42;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'qwert' with focus on 'PwEntryForm.MTabEntry.UserName'.", repo.PwEntryForm.MTabEntry.UserNameInfo, new RecordItemIndex(10));
            repo.PwEntryForm.MTabEntry.UserName.PressKeys("qwert");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PwEntryForm.MTabEntry.Password' at 157;8.", repo.PwEntryForm.MTabEntry.PasswordInfo, new RecordItemIndex(11));
            repo.PwEntryForm.MTabEntry.Password.Click("157;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'PwEntryForm.MTabEntry.Password' at 157;8.", repo.PwEntryForm.MTabEntry.PasswordInfo, new RecordItemIndex(12));
            repo.PwEntryForm.MTabEntry.Password.Click(System.Windows.Forms.MouseButtons.Right, "157;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'KeePass.SelectAll' at 73;7.", repo.KeePass.SelectAllInfo, new RecordItemIndex(13));
            repo.KeePass.SelectAll.Click("73;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'asdfg' with focus on 'PwEntryForm.MTabEntry.Password'.", repo.PwEntryForm.MTabEntry.PasswordInfo, new RecordItemIndex(14));
            repo.PwEntryForm.MTabEntry.Password.PressKeys("asdfg");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PwEntryForm.MTabEntry.Repeat' at 167;11.", repo.PwEntryForm.MTabEntry.RepeatInfo, new RecordItemIndex(15));
            repo.PwEntryForm.MTabEntry.Repeat.Click("167;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'PwEntryForm.MTabEntry.Repeat' at 166;8.", repo.PwEntryForm.MTabEntry.RepeatInfo, new RecordItemIndex(16));
            repo.PwEntryForm.MTabEntry.Repeat.Click(System.Windows.Forms.MouseButtons.Right, "166;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'KeePass.SelectAll' at 55;3.", repo.KeePass.SelectAllInfo, new RecordItemIndex(17));
            repo.KeePass.SelectAll.Click("55;3");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'asdfg' with focus on 'PwEntryForm.MTabEntry.Repeat'.", repo.PwEntryForm.MTabEntry.RepeatInfo, new RecordItemIndex(18));
            repo.PwEntryForm.MTabEntry.Repeat.PressKeys("asdfg");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PwEntryForm.MTabEntry.URL' at 35;9.", repo.PwEntryForm.MTabEntry.URLInfo, new RecordItemIndex(19));
            repo.PwEntryForm.MTabEntry.URL.Click("35;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'www.' with focus on 'PwEntryForm.MTabEntry.URL'.", repo.PwEntryForm.MTabEntry.URLInfo, new RecordItemIndex(20));
            repo.PwEntryForm.MTabEntry.URL.PressKeys("www.");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'plmn.com' with focus on 'PwEntryForm.MTabEntry.URL'.", repo.PwEntryForm.MTabEntry.URLInfo, new RecordItemIndex(21));
            repo.PwEntryForm.MTabEntry.URL.PressKeys("plmn.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PwEntryForm.MTabEntry.Notes' at 50;4.", repo.PwEntryForm.MTabEntry.NotesInfo, new RecordItemIndex(22));
            repo.PwEntryForm.MTabEntry.Notes.Click("50;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'hello...' with focus on 'PwEntryForm.MTabEntry.Notes'.", repo.PwEntryForm.MTabEntry.NotesInfo, new RecordItemIndex(23));
            repo.PwEntryForm.MTabEntry.Notes.PressKeys("hello...");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PwEntryForm.MBtnStandardExpires' at 11;10.", repo.PwEntryForm.MBtnStandardExpiresInfo, new RecordItemIndex(24));
            repo.PwEntryForm.MBtnStandardExpires.Click("11;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'KeePass.MenuItem2Weeks' at 34;13.", repo.KeePass.MenuItem2WeeksInfo, new RecordItemIndex(25));
            repo.KeePass.MenuItem2Weeks.Click("34;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PwEntryForm.MBtnOK' at 47;7.", repo.PwEntryForm.MBtnOKInfo, new RecordItemIndex(26));
            repo.PwEntryForm.MBtnOK.Click("47;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.File' at 23;11.", repo.MainForm.FileInfo, new RecordItemIndex(27));
            repo.MainForm.File.Click("23;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'KeePass.Save' at 51;13.", repo.KeePass.SaveInfo, new RecordItemIndex(28));
            repo.KeePass.Save.Click("51;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.Close' at 20;8.", repo.MainForm.CloseInfo, new RecordItemIndex(29));
            repo.MainForm.Close.Click("20;8");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
